import = ["/Users/rudyard/.config/alacritty/gruvbox.toml"]

[font]
builtin_box_drawing = true
size = 14

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Light Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Control"

[[keyboard.bindings]]
action = "First"
key = "H"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Last"
key = "L"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Copy"
key = "Space"
mode = "Vi"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Space"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "Space"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "Vi"

[[keyboard.bindings]]
action = "Open"
key = "Return"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Return"
mode = "Vi|~Search"
mods = "Shift"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "full"
startup_mode = "Maximized"
